name: Meeting Prep Bot Scheduled Run

on:
  schedule:
    # Runs every day at 6:00am UTC. Adjust as needed.
    - cron: '0 6 * * *'
  workflow_dispatch: # Allows you to trigger manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Meeting Prep Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NBH_GDRIVE_FOLDER_ID: ${{ secrets.NBH_GDRIVE_FOLDER_ID }}
          # Add other secrets/env vars here as needed
        run: |
          python meeting-prep_running_version.py
